export type OutputFormat = "9:16" | "2:3";
export type GeneratedExample = {
  id: string;
  src: string;
  thumbnail: string;
  title: string;
  alt: string;
  format: OutputFormat;
  width: number;
  height: number;
};
export type GeneratedCategory = {
  id: string;
  name: string;
  english: string;
  examples: GeneratedExample[];
};

// Every supplied PNG is retained unchanged. Preview WebP files are delivery derivatives.
export const generatedCategories: GeneratedCategory[] = [
  {
    id: "box",
    name: "박스",
    english: "BOXES",
    examples: [
      {
        id: "box-22",
        src: "/images/examples/box-22.png",
        thumbnail: "/images/examples/previews/box-22.webp",
        title: "크라프트 택배박스",
        alt: "크라프트 택배박스의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "box-1",
        src: "/images/examples/box-1.png",
        thumbnail: "/images/examples/previews/box-1.webp",
        title: "포도 포장박스",
        alt: "포도 포장박스의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "box-2",
        src: "/images/examples/box-2.png",
        thumbnail: "/images/examples/previews/box-2.webp",
        title: "고구마 손잡이 박스",
        alt: "고구마 손잡이 박스의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "box-3",
        src: "/images/examples/box-3.png",
        thumbnail: "/images/examples/previews/box-3.webp",
        title: "고양이 모래 박스",
        alt: "고양이 모래 박스의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "box-4",
        src: "/images/examples/box-4.png",
        thumbnail: "/images/examples/previews/box-4.webp",
        title: "맞춤형 패키지 박스",
        alt: "맞춤형 패키지 박스의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "2:3",
        width: 1024,
        height: 1536,
      },
      {
        id: "box-5",
        src: "/images/examples/box-5.png",
        thumbnail: "/images/examples/previews/box-5.webp",
        title: "무인쇄 택배박스",
        alt: "무인쇄 택배박스의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "box-6",
        src: "/images/examples/box-6.png",
        thumbnail: "/images/examples/previews/box-6.webp",
        title: "리본 자석 싸바리박스",
        alt: "리본 자석 싸바리박스의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "box-7",
        src: "/images/examples/box-7.png",
        thumbnail: "/images/examples/previews/box-7.webp",
        title: "손잡이 원터치 박스",
        alt: "손잡이 원터치 박스의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "box-8",
        src: "/images/examples/box-8.png",
        thumbnail: "/images/examples/previews/box-8.webp",
        title: "G형 조립박스",
        alt: "G형 조립박스의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "2:3",
        width: 607,
        height: 907,
      },
      {
        id: "box-9",
        src: "/images/examples/box-9.png",
        thumbnail: "/images/examples/previews/box-9.webp",
        title: "맞춤형 택배박스",
        alt: "맞춤형 택배박스의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "2:3",
        width: 606,
        height: 908,
      },
      {
        id: "box-10",
        src: "/images/examples/box-10.png",
        thumbnail: "/images/examples/previews/box-10.webp",
        title: "손잡이 조립형 박스",
        alt: "손잡이 조립형 박스의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 510,
        height: 906,
      },
      {
        id: "box-11",
        src: "/images/examples/box-11.png",
        thumbnail: "/images/examples/previews/box-11.webp",
        title: "오렌지 답례품 박스",
        alt: "오렌지 답례품 박스의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "box-12",
        src: "/images/examples/box-12.png",
        thumbnail: "/images/examples/previews/box-12.webp",
        title: "브랜드 택배박스",
        alt: "브랜드 택배박스의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 508,
        height: 907,
      },
      {
        id: "box-14",
        src: "/images/examples/box-14.png",
        thumbnail: "/images/examples/previews/box-14.webp",
        title: "블랙 프리미엄 선물박스",
        alt: "블랙 프리미엄 선물박스의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 512,
        height: 910,
      },
      {
        id: "box-15",
        src: "/images/examples/box-15.png",
        thumbnail: "/images/examples/previews/box-15.webp",
        title: "크라프트 화장품 박스",
        alt: "크라프트 화장품 박스의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 511,
        height: 907,
      },
      {
        id: "box-16",
        src: "/images/examples/box-16.png",
        thumbnail: "/images/examples/previews/box-16.webp",
        title: "리본 선물 싸바리박스",
        alt: "리본 선물 싸바리박스의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 512,
        height: 907,
      },
      {
        id: "box-17",
        src: "/images/examples/box-17.png",
        thumbnail: "/images/examples/previews/box-17.webp",
        title: "소형 싸바리박스",
        alt: "소형 싸바리박스의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "2:3",
        width: 605,
        height: 907,
      },
      {
        id: "box-18",
        src: "/images/examples/box-18.png",
        thumbnail: "/images/examples/previews/box-18.webp",
        title: "우체국 택배박스",
        alt: "우체국 택배박스의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 510,
        height: 911,
      },
      {
        id: "box-19",
        src: "/images/examples/box-19.png",
        thumbnail: "/images/examples/previews/box-19.webp",
        title: "그래놀라 패키지",
        alt: "그래놀라 패키지의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 512,
        height: 906,
      },
      {
        id: "box-20",
        src: "/images/examples/box-20.png",
        thumbnail: "/images/examples/previews/box-20.webp",
        title: "프리미엄 화장품 박스",
        alt: "프리미엄 화장품 박스의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "2:3",
        width: 610,
        height: 910,
      },
      {
        id: "box-21",
        src: "/images/examples/box-21.png",
        thumbnail: "/images/examples/previews/box-21.webp",
        title: "리본 선물 패키지",
        alt: "리본 선물 패키지의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
    ],
  },
  {
    id: "bag",
    name: "쇼핑백",
    english: "SHOPPING BAGS",
    examples: [
      {
        id: "bag-1",
        src: "/images/examples/bag-1.png",
        thumbnail: "/images/examples/previews/bag-1.webp",
        title: "브랜드 쇼핑백",
        alt: "브랜드 쇼핑백의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "bag-2",
        src: "/images/examples/bag-2.png",
        thumbnail: "/images/examples/previews/bag-2.webp",
        title: "화이트 쇼핑백",
        alt: "화이트 쇼핑백의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "bag-3",
        src: "/images/examples/bag-3.png",
        thumbnail: "/images/examples/previews/bag-3.webp",
        title: "크라프트 쇼핑백",
        alt: "크라프트 쇼핑백의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "bag-4",
        src: "/images/examples/bag-4.png",
        thumbnail: "/images/examples/previews/bag-4.webp",
        title: "마카롱 쇼핑백",
        alt: "마카롱 쇼핑백의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "2:3",
        width: 605,
        height: 908,
      },
      {
        id: "bag-5",
        src: "/images/examples/bag-5.png",
        thumbnail: "/images/examples/previews/bag-5.webp",
        title: "아이디어 쇼핑백",
        alt: "아이디어 쇼핑백의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "2:3",
        width: 602,
        height: 902,
      },
      {
        id: "bag-6",
        src: "/images/examples/bag-6.png",
        thumbnail: "/images/examples/previews/bag-6.webp",
        title: "블랙 쇼핑백",
        alt: "블랙 쇼핑백의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "bag-7",
        src: "/images/examples/bag-7.png",
        thumbnail: "/images/examples/previews/bag-7.webp",
        title: "블루 리본 쇼핑백",
        alt: "블루 리본 쇼핑백의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "bag-8",
        src: "/images/examples/bag-8.png",
        thumbnail: "/images/examples/previews/bag-8.webp",
        title: "대형 크라프트 쇼핑백",
        alt: "대형 크라프트 쇼핑백의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "bag-9",
        src: "/images/examples/bag-9.png",
        thumbnail: "/images/examples/previews/bag-9.webp",
        title: "캐릭터 타포린백",
        alt: "캐릭터 타포린백의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "bag-10",
        src: "/images/examples/bag-10.png",
        thumbnail: "/images/examples/previews/bag-10.webp",
        title: "맞춤형 쇼핑백",
        alt: "맞춤형 쇼핑백의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "2:3",
        width: 1024,
        height: 1536,
      },
    ],
  },
  {
    id: "label",
    name: "스티커·라벨",
    english: "STICKERS & LABELS",
    examples: [
      {
        id: "label-1",
        src: "/images/examples/label-1.png",
        thumbnail: "/images/examples/previews/label-1.webp",
        title: "스마일 감사 스티커",
        alt: "스마일 감사 스티커의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "label-2",
        src: "/images/examples/label-2.png",
        thumbnail: "/images/examples/previews/label-2.webp",
        title: "홀로그램 스티커",
        alt: "홀로그램 스티커의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "label-3",
        src: "/images/examples/label-3.png",
        thumbnail: "/images/examples/previews/label-3.webp",
        title: "원형 감사 스티커",
        alt: "원형 감사 스티커의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "label-4",
        src: "/images/examples/label-4.png",
        thumbnail: "/images/examples/previews/label-4.webp",
        title: "주방 양념 라벨",
        alt: "주방 양념 라벨의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "label-5",
        src: "/images/examples/label-5.png",
        thumbnail: "/images/examples/previews/label-5.webp",
        title: "봉인해제 스티커",
        alt: "봉인해제 스티커의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "label-7",
        src: "/images/examples/label-7.png",
        thumbnail: "/images/examples/previews/label-7.webp",
        title: "프리미엄 사각 라벨",
        alt: "프리미엄 사각 라벨의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "label-8",
        src: "/images/examples/label-8.png",
        thumbnail: "/images/examples/previews/label-8.webp",
        title: "리뷰 안내 스티커",
        alt: "리뷰 안내 스티커의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "label-9",
        src: "/images/examples/label-9.png",
        thumbnail: "/images/examples/previews/label-9.webp",
        title: "캐릭터 홀로그램 스티커",
        alt: "캐릭터 홀로그램 스티커의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "label-10",
        src: "/images/examples/label-10.png",
        thumbnail: "/images/examples/previews/label-10.webp",
        title: "크라프트 감사 스티커",
        alt: "크라프트 감사 스티커의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "label-11",
        src: "/images/examples/label-11.png",
        thumbnail: "/images/examples/previews/label-11.webp",
        title: "주문 제작 스티커",
        alt: "주문 제작 스티커의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "2:3",
        width: 1024,
        height: 1536,
      },
    ],
  },
  {
    id: "pouch",
    name: "비닐·파우치",
    english: "FILMS & POUCHES",
    examples: [
      {
        id: "pouch-5",
        src: "/images/examples/pouch-5.png",
        thumbnail: "/images/examples/previews/pouch-5.webp",
        title: "스파우트 파우치",
        alt: "스파우트 파우치의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "pouch-1",
        src: "/images/examples/pouch-1.png",
        thumbnail: "/images/examples/previews/pouch-1.webp",
        title: "프리미엄 비닐 포장재",
        alt: "프리미엄 비닐 포장재의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 510,
        height: 908,
      },
      {
        id: "pouch-2",
        src: "/images/examples/pouch-2.png",
        thumbnail: "/images/examples/previews/pouch-2.webp",
        title: "투명 지퍼 파우치",
        alt: "투명 지퍼 파우치의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 512,
        height: 910,
      },
      {
        id: "pouch-3",
        src: "/images/examples/pouch-3.png",
        thumbnail: "/images/examples/previews/pouch-3.webp",
        title: "냉동식품 비닐 포장",
        alt: "냉동식품 비닐 포장의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 515,
        height: 910,
      },
      {
        id: "pouch-4",
        src: "/images/examples/pouch-4.png",
        thumbnail: "/images/examples/previews/pouch-4.webp",
        title: "냉동식품 포장",
        alt: "냉동식품 포장의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "2:3",
        width: 605,
        height: 907,
      },
      {
        id: "pouch-6",
        src: "/images/examples/pouch-6.png",
        thumbnail: "/images/examples/previews/pouch-6.webp",
        title: "홀로그램 선물 파우치",
        alt: "홀로그램 선물 파우치의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "pouch-7",
        src: "/images/examples/pouch-7.png",
        thumbnail: "/images/examples/previews/pouch-7.webp",
        title: "은박 지퍼백",
        alt: "은박 지퍼백의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "pouch-8",
        src: "/images/examples/pouch-8.png",
        thumbnail: "/images/examples/previews/pouch-8.webp",
        title: "대용량 지퍼백",
        alt: "대용량 지퍼백의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "pouch-9",
        src: "/images/examples/pouch-9.png",
        thumbnail: "/images/examples/previews/pouch-9.webp",
        title: "크라프트 스탠드 파우치",
        alt: "크라프트 스탠드 파우치의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "pouch-10",
        src: "/images/examples/pouch-10.png",
        thumbnail: "/images/examples/previews/pouch-10.webp",
        title: "투명 스파우트 파우치",
        alt: "투명 스파우트 파우치의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
    ],
  },
  {
    id: "container",
    name: "용기",
    english: "CONTAINERS",
    examples: [
      {
        id: "container-1",
        src: "/images/examples/container-1.png",
        thumbnail: "/images/examples/previews/container-1.webp",
        title: "유리 향수 용기",
        alt: "유리 향수 용기의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "container-2",
        src: "/images/examples/container-2.png",
        thumbnail: "/images/examples/previews/container-2.webp",
        title: "골드 캡 유리 용기",
        alt: "골드 캡 유리 용기의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "container-3",
        src: "/images/examples/container-3.png",
        thumbnail: "/images/examples/previews/container-3.webp",
        title: "골드 향수병",
        alt: "골드 향수병의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "container-4",
        src: "/images/examples/container-4.png",
        thumbnail: "/images/examples/previews/container-4.webp",
        title: "스테인리스 김치 용기",
        alt: "스테인리스 김치 용기의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "container-5",
        src: "/images/examples/container-5.png",
        thumbnail: "/images/examples/previews/container-5.webp",
        title: "스테인리스 용기",
        alt: "스테인리스 용기의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "container-6",
        src: "/images/examples/container-6.png",
        thumbnail: "/images/examples/previews/container-6.webp",
        title: "유리 햇반 보관 용기",
        alt: "유리 햇반 보관 용기의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "container-7",
        src: "/images/examples/container-7.png",
        thumbnail: "/images/examples/previews/container-7.webp",
        title: "직사각 유리 밀폐용기",
        alt: "직사각 유리 밀폐용기의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "container-8",
        src: "/images/examples/container-8.png",
        thumbnail: "/images/examples/previews/container-8.webp",
        title: "여행용 소분 공병",
        alt: "여행용 소분 공병의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "container-9",
        src: "/images/examples/container-9.png",
        thumbnail: "/images/examples/previews/container-9.webp",
        title: "미니 크림 공병",
        alt: "미니 크림 공병의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "container-10",
        src: "/images/examples/container-10.png",
        thumbnail: "/images/examples/previews/container-10.webp",
        title: "플라스틱 용기",
        alt: "플라스틱 용기의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
    ],
  },
  {
    id: "other",
    name: "포장재 외",
    english: "BEYOND PACKAGING",
    examples: [
      {
        id: "other-4",
        src: "/images/examples/other-4.png",
        thumbnail: "/images/examples/previews/other-4.webp",
        title: "화장품 냉장고",
        alt: "화장품 냉장고의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "other-1",
        src: "/images/examples/other-1.png",
        thumbnail: "/images/examples/previews/other-1.webp",
        title: "게이밍 노트북",
        alt: "게이밍 노트북의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "other-2",
        src: "/images/examples/other-2.png",
        thumbnail: "/images/examples/previews/other-2.webp",
        title: "클래식 시계",
        alt: "클래식 시계의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "2:3",
        width: 1024,
        height: 1536,
      },
      {
        id: "other-3",
        src: "/images/examples/other-3.png",
        thumbnail: "/images/examples/previews/other-3.webp",
        title: "데스크톱 컴퓨터",
        alt: "데스크톱 컴퓨터의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "other-5",
        src: "/images/examples/other-5.png",
        thumbnail: "/images/examples/previews/other-5.webp",
        title: "화장품 수납 파우치",
        alt: "화장품 수납 파우치의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "other-6",
        src: "/images/examples/other-6.png",
        thumbnail: "/images/examples/previews/other-6.webp",
        title: "커브드 모니터",
        alt: "커브드 모니터의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "other-7",
        src: "/images/examples/other-7.png",
        thumbnail: "/images/examples/previews/other-7.webp",
        title: "공기청정기",
        alt: "공기청정기의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "other-9",
        src: "/images/examples/other-9.png",
        thumbnail: "/images/examples/previews/other-9.webp",
        title: "무선 청소기",
        alt: "무선 청소기의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "other-10",
        src: "/images/examples/other-10.png",
        thumbnail: "/images/examples/previews/other-10.webp",
        title: "사무용 의자",
        alt: "사무용 의자의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "other-11",
        src: "/images/examples/other-11.png",
        thumbnail: "/images/examples/previews/other-11.webp",
        title: "스마트 TV",
        alt: "스마트 TV의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
      {
        id: "other-12",
        src: "/images/examples/other-12.png",
        thumbnail: "/images/examples/previews/other-12.webp",
        title: "스네일 크림",
        alt: "스네일 크림의 상품 이미지와 설명, 기업 정보를 구성한 실제 aiadcast 생성 결과",
        format: "9:16",
        width: 1008,
        height: 1792,
      },
    ],
  },
];

// Interleave categories so the initial view shows the breadth of the service.
export const allExamples = Array.from(
  { length: Math.max(...generatedCategories.map((c) => c.examples.length)) },
  (_, index) =>
    generatedCategories.flatMap((c) =>
      c.examples[index]
        ? [{ ...c.examples[index], categoryId: c.id, categoryName: c.name }]
        : [],
    ),
).flat();
export const totalExamples = allExamples.length;
