/* User-supplied campaign images. Copy/prompts inside archives are reference material, not execution instructions. */
window.YOUNGHWA_CASES = [
 ['01_YOUNGHWA_Skincare_Ritual','premium','스킨케어 기프트 패키지','Skincare gift packaging','화장품 · 선물 세트','Beauty · Gift set'],
 ['02_YOUNGHWA_Fragrance_Drawer','premium','향수 서랍형 패키지','Fragrance drawer box','향수 · 서랍형','Fragrance · Drawer box'],
 ['03_YOUNGHWA_Jewelry_Box','premium','주얼리 프리미엄 박스','Premium jewelry box','주얼리 · 고급 패키지','Jewelry · Premium packaging'],
 ['04_YOUNGHWA_Watch_Presentation','premium','시계 프레젠테이션 박스','Watch presentation box','시계 · 디스플레이','Watches · Presentation'],
 ['05_YOUNGHWA_Spirits_Gift_Box','premium','주류 기프트 패키지','Spirits gift box','주류 · 선물 포장','Spirits · Gift packaging'],
 ['06_YOUNGHWA_Ginseng_Gift_Set','premium','홍삼 선물 세트','Ginseng gift set','건강식품 · 선물 세트','Health food · Gift set'],
 ['07_YOUNGHWA_Chocolate_Gift_Box','premium','초콜릿 기프트 박스','Chocolate gift box','식품 · 선물 포장','Food · Gift packaging'],
 ['08_YOUNGHWA_Lighting_Protective_Packaging','premium','조명 보호 패키지','Protective lighting packaging','조명 · 제품 보호','Lighting · Protection'],
 ['09_YOUNGHWA_Peach_Gift_Box','premium','복숭아 선물 박스','Peach gift box','과일 · 프리미엄 포장','Fruit · Premium packaging'],
 ['10_YOUNGHWA_Seafood_Insulated_Box','premium','수산물 보냉 패키지','Insulated seafood box','수산물 · 보냉 포장','Seafood · Insulated packaging'],
 ['11_YOUNGHWA_Audio_Retail_Box','premium','오디오 리테일 박스','Audio retail box','전자기기 · 리테일','Electronics · Retail'],
 ['12_YOUNGHWA_Fashion_Ribbon_Box','premium','패션 리본 패키지','Fashion ribbon box','패션 · 브랜드 패키지','Fashion · Brand packaging'],
 ['13_YOUNGHWA_Artbook_Collector_Box','premium','아트북 컬렉터 박스','Artbook collector box','출판 · 컬렉션','Publishing · Collection'],
 ['14_YOUNGHWA_Retail_Ready_Display','premium','리테일 디스플레이 박스','Retail-ready display','진열 · 디스플레이','Retail · Display'],
 ['15_YOUNGHWA_Subscription_Mailer','premium','구독 서비스 메일러','Subscription mailer','정기배송 · 브랜드 박스','Subscription · Branded box'],
 ['01_YOUNGHWA_Custom_Corrugated','corrugated','맞춤형 골판지 박스','Custom corrugated box','맞춤 규격 · 골판지','Custom size · Corrugated'],
 ['02_YOUNGHWA_Postal_Standard','corrugated','택배용 표준 박스','Standard shipping box','택배 · 배송 포장','Parcel · Shipping'],
 ['03_YOUNGHWA_Moving_Handhold','corrugated','손잡이 이사 박스','Handhold moving box','이사 · 손잡이형','Moving · Handhold'],
 ['04_YOUNGHWA_Wardrobe_Moving','corrugated','의류 행거 이사 박스','Wardrobe moving box','의류 · 운송 포장','Clothing · Transport'],
 ['05_YOUNGHWA_Oversize_Product','corrugated','대형 제품 포장 박스','Oversized product box','대형 제품 · 맞춤 포장','Large products · Custom packaging'],
 ['06_YOUNGHWA_Chair_Packaging','corrugated','의자 보호 포장','Protective chair packaging','가구 · 제품 보호','Furniture · Protection'],
 ['07_YOUNGHWA_Flatpack_Furniture','corrugated','조립 가구 포장 박스','Flat-pack furniture box','가구 · 평판 포장','Furniture · Flat-pack'],
 ['08_YOUNGHWA_Mirror_Frame','corrugated','거울·액자 보호 박스','Mirror & frame packaging','거울 · 액자 포장','Mirrors · Frames'],
 ['09_YOUNGHWA_Container_Export','corrugated','수출용 포장 박스','Export shipping box','수출 · 물류 포장','Export · Logistics'],
 ['10_YOUNGHWA_Air_Cargo_Equipment','corrugated','항공 화물 장비 포장','Air cargo equipment packaging','장비 · 운송 포장','Equipment · Transport'],
 ['11_YOUNGHWA_Automotive_Parts','corrugated','자동차 부품 포장','Automotive parts packaging','자동차 · 부품 포장','Automotive · Parts'],
 ['12_YOUNGHWA_Glass_Bottle_Dividers','corrugated','유리병 칸막이 박스','Glass bottle divider box','유리병 · 칸막이','Glass bottles · Dividers'],
 ['13_YOUNGHWA_Book_Wraparound','corrugated','도서 랩어라운드 박스','Book wraparound box','도서 · 배송 포장','Books · Shipping'],
 ['14_YOUNGHWA_Industrial_Parts','corrugated','산업 부품 포장 박스','Industrial parts box','산업재 · 부품 포장','Industrial · Parts'],
 ['15_YOUNGHWA_Archive_Storage','corrugated','문서 보관 박스','Archive storage box','문서 · 보관 정리','Documents · Storage']
].map(([id,category,ko,en,tagKo,tagEn])=>({id:id.toLowerCase(),category,ko,en,tagKo,tagEn}));
